title: "Lab.io - Adam Butler"
display_title: "Lab.io"
email: adam@lab.io
# description: "Personal website of Adam Butler. Web Developer in Bristol, UK."
url: "http://lab.io"
twitter_username: labfoo
github_username:  adambutler

# Build settings
markdown: kramdown
